<!Doctype html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Movies In The park</title>
        <link rel="stylesheet" href="style/main1.css" />
    </head>
    <body>
        <div class="row">
            <div class="col-md-2">left</div>
            <div class="col-md-8">

                <?php

$this->renderBody();

                ?>


            </div>
            <div class="col-md-2">right</div>



        </div>
    </body>
</html>