<?php $this->layout("_layout.phtml") ?>
<tr>
    <td style="width: 100%;">
        <p><strong>The Bandshell area of Waterloo Park is in the WEST end of the park.</strong></p>
        <p align="center"><strong> </strong><a href="http://maps.google.ca/maps/ms?hl=en&amp;ie=UTF8&amp;msa=0&amp;msid=112848998992363548066.00044ca8cfc876f9ff7d2&amp;ll=43.465691,-80.532446&amp;spn=0.021803,0.030041&amp;z=14&amp;source=embed" target="_blank" style="text-align: left;">View&nbsp;Map</a></p>
        <p align="center">or</p>
        <p align="center"><a href="http://maps.google.ca/maps?daddr=Bandshell+@43.466173,-80.537574&amp;geocode=&amp;dirflg=&amp;saddr=&amp;f=d&amp;hl=en&amp;sll=43.473664,-80.532446&amp;sspn=0.023793,0.056133&amp;ie=UTF8&amp;z=15" target="_blank">Use the "<em>get directions</em>" on Google Maps. </a></p>
        <p> You have several options for parking here: </p>
        <ol>
            <li>Westmount Rd. - Enter the park gate between David Bauer Drive &amp; University Ave. </li>
            <li>Seagram Dr. - Enter from Seagram Dr. (next to the railway crossing)</li>
            <li>David Bauer Dr. - There is a parking lot across the street from the Waterloo Recreation Complex. Walk past the baseball diamonds, and past the Wesmount Rd. parking lot.</li>
            <li>Westmount Plaza.</li>
            <li>Waterloo Recreation Complex</li>
            <li>Park at home and walk.</li>
            <li>Take the <a href="http://www.grt.ca/" target="_blank">bus</a>.</li>
        </ol>
    </td>
</tr>
