<?php $this->layout("_layout.phtml") ?>
<div style="text-align: center;">
    <p style="text-align:center; font-family:Arial; font-size:30px; font-weight:bolder; margin:10px auto;">2015 Summer Schedule</p>
    <span style="font-family: Arial;">Under the stars and on Canada's largest outdoor screen! </span>
    <br>
    <span style="font-family: Arial;">Music &amp; Movies In The Park is back!
        <br>
        Music starts at 7:00. Movie starts at dusk.</span>
</div>
<div style="text-align: center; font-family: Arial;">
    <br>
    <a style="font-family: Arial;" href="movie">Thursday Jul. 9</a>
    <br>
    <br>
    <br>
    <a style="font-family: Arial;" href="movie">Thursday Jul. 23</a>
    <br>
    <br>
    <br>
    <a style="font-family: Arial;" href="movie">Thursday Aug. 6</a>
    <br>
    <br>
    <br>
    <a style="font-family: Arial;" href="movie">Thursday Aug. 20</a>
    <br>
    <br>
</div>
