<?php $this->layout("_layout.phtml") ?>
<tr>
    <td style="width: 100%;">
        <font face="Arial" size="2">
            <span style="font-size: 10pt; font-family: Arial;"></span>
        </font>
        <div>
            <span style="font-weight: bold;">Thursday July 9</span> - The SpongeBob Movie: Sponge Out of Water (<a href="https://www.youtube.com/watch?v=TGjbpO1toTc">Trailer</a>)
            <br>Musical guest: <a href="http://www.ericktraplin.com/">Erick Traplin (children's performer)</a>
            <br>
            <br>
            <br>
            <span style="font-weight: bold;">Thursday July 23</span> - The Sound of Music (<a href="https://www.youtube.com/watch?v=UY6uw3WpPzY">Trailer</a>)
            <br>Musical guest: <a href="http://www.waterstreetband.com/">Waterstreet Blues Band</a>
            <br>
            <br>
            <br>
            <span style="font-weight: bold;">Thursday August 6</span> - Home (<a href="https://www.youtube.com/watch?v=VCqyvd_djLQ">Trailer</a>)
            <br>Musical guest: <a href="#">TBA</a>
            <br>
            <br>
            <br>
            <span style="font-weight: bold;">Thursday August 20</span> - Fast & Furious 7 (<a href="https://www.youtube.com/watch?v=Skpu5HaVkOc">Trailer</a>)
            <br>Musical guest: <a href="https://www.facebook.com/thebaudelairesband">The Baudelaires</a> 
            <br>
            <br>
            <br>
        </div>
    </td>
</tr>
