<?php $this->layout("_layout.phtml") ?>
<tr>
    <td style="width: 100%;">
        <img style="width: 400px; height: 266px;" alt="" src="img/pics/crowd-01-500.jpg">
        <br>2008<br>
        <img style="width: 400px; height: 266px;" alt="" src="img/pics/crowd-screen-01-500.jpg">
        <br>2008<br>
        <img style="width: 400px; height: 300px;" alt="" src="img/pics/img105.jpg">
        <br>2008<br>
    </td>
</tr>
<tr>
